:verbose: true
development:
  :concurrency: 20
staging:
  :concurrency: 10
production:
  :concurrency: 10


:queues:
  - default
  - import_file
  - import_process
  - import_mira_files_process
  - import_clicd_files_process
  - filter_claims_process
  - filter_policies_process
  - filter_accounts_process
  - import_democ_process
  - import_ratefile_process
  - import_pdemo_process
  - import_pcomb_process
  - import_mrcls_process
  - import_mremps_process
  - import_phmgns_process
  - import_sc230_process
  - import_pemhs_process
  - import_pcovgs_process
  - import_clicd_data
  - group_rating_calculate
  - mira_clicd_process
  - import_mira_data
  - import_weekly_mira_data
  - all_representatives_process
  - representative_all_account_rating
  - parse_file
  - group_rating_step_one
  - group_rating_step_two
  - group_rating_step_two_partial
  - group_rating_step_three
  - group_rating_step_three_a
  - group_rating_step_three_b
  - group_rating_step_three_c
  - group_rating_step_four
  - group_rating_step_five
  - group_rating_step_six
  - group_rating_step_seven
  - group_rating_step_eight
  - predecessor_account_update_create_process
  - group_rating_all_create_process
  - group_rating_all_create
  - policy_update_create_process
  - policy_update_create
  - policy_coverage_update_create_process
  - policy_coverage_update_create
  - manual_class_update_create_process
  - manual_class_update_create
  - payroll_update_create_process
  - payroll_update_create
  - account_group_rating_process
  - account_group_rating_calc
  - claim_update_create
  - claim_update_create_process
  - policy_export
  - account_policy_export
  - manual_class_export
  - weekly_request
  - group_rating_mark_complete
  - handle_manual_policy_calculations
  - handle_manual_policy_calculations_process
  - generate_quote_process
  - generate_quote
  - generate_all_quote_packet
  - delete_quote_process
  - delete_quote
