development:
  :concurrency: 5
production:
  :concurrency: 20

:queues:
  - default
  - import_file
  - import_process
  - parse_file
  - group_rating_step_one
  - group_rating_step_two
  - group_rating_step_two_partial
  - group_rating_step_three
  - group_rating_step_three_a
  - group_rating_step_three_b
  - group_rating_step_three_c
  - group_rating_step_four
  - group_rating_step_five
  - group_rating_step_six
  - group_rating_step_seven
  - group_rating_step_eight
  - predecessor_account_update_create_process
  - group_rating_all_create_process
  - group_rating_all_create
  - policy_update_create_process
  - policy_update_create
  - policy_coverage_update_create_process
  - policy_coverage_update_create
  - manual_class_update_create_process
  - manual_class_update_create
  - payroll_update_create_process
  - payroll_update_create
  - account_group_rating_process
  - account_group_rating_calc
  - claim_update_create
  - claim_update_create_process
  - policy_export
  - account_policy_export
