class CreateSc220Rec3EmployerArTransactions < ActiveRecord::Migration
  def change
    create_table :sc220_rec3_employer_ar_transactions do |t|
      t.integer :representative_number
      t.integer :representative_type
      t.string :descriptionar
      t.integer :record_type
      t.integer :request_type
      t.string :policy_type
      t.integer :policy_number
      t.integer :business_sequence_number
      t.date :trans_date
      t.string :invoice_number
      t.string :billing_trans_status_code
      t.float :trans_amount
      t.string :trans_type
      t.float :paid_amount
      t.date :n2nd_trans_date
      t.string :n2nd_invoice_number
      t.string :n2nd_billing_trans_status_code
      t.float :n2nd_trans_amount
      t.string :n2nd_trans_type
      t.float :n2nd_paid_amount
      t.date :n3rd_trans_date
      t.string :n3rd_invoice_number
      t.string :n3rd_billing_trans_status_code
      t.float :n3rd_trans_amount
      t.string :n3rd_trans_type
      t.float :n3rd_paid_amount
      t.date :n4th_trans_date
      t.string :n4th_invoice_number
      t.string :n4th_billing_trans_status_code
      t.float :n4th_trans_amount
      t.string :n4th_trans_type
      t.float :n4th_paid_amount
      t.date :n5th_trans_date
      t.string :n5th_invoice_number
      t.string :n5th_billing_trans_status_code
      t.float :n5th_trans_amount
      t.string :n5th_trans_type
      t.float :n5th_paid_amount
      t.date :n6th_trans_date
      t.string :n6th_invoice_number
      t.string :n6th_billing_trans_status_code
      t.float :n6th_trans_amount
      t.string :n6th_trans_type
      t.float :n6th_paid_amount
      t.date :n7th_trans_date
      t.string :n7th_invoice_number
      t.string :n7th_billing_trans_status_code
      t.float :n7th_trans_amount
      t.string :n7th_trans_type
      t.float :n7th_paid_amount
      t.date :n8th_trans_date
      t.string :n8th_invoice_number
      t.string :n8th_billing_trans_status_code
      t.float :n8th_trans_amount
      t.string :n8th_trans_type
      t.float :n8th_paid_amount
      t.date :n9th_trans_date
      t.string :n9th_invoice_number
      t.string :n9th_billing_trans_status_code
      t.float :n9th_trans_amount
      t.string :n9th_trans_type
      t.float :n9th_paid_amount
      t.date :n10th_trans_date
      t.string :n10th_invoice_number
      t.string :n10th_billing_trans_status_code
      t.float :n10th_trans_amount
      t.string :n10th_trans_type
      t.float :n10th_paid_amount
      t.date :n11th_trans_date
      t.string :n11th_invoice_number
      t.string :n11th_billing_trans_status_code
      t.float :n11th_trans_amount
      t.string :n11th_trans_type
      t.float :n11th_paid_amount
      t.date :n12th_trans_date
      t.string :n12th_invoice_number
      t.string :n12th_billing_trans_status_code
      t.float :n12th_trans_amount
      t.string :n12th_trans_type
      t.float :n12th_paid_amount
      t.date :n13th_trans_date
      t.string :n13th_invoice_number
      t.string :n13th_billing_trans_status_code
      t.float :n13th_trans_amount
      t.string :n13th_trans_type
      t.float :n13th_paid_amount
      t.date :n14th_trans_date
      t.string :n14th_invoice_number
      t.string :n14th_billing_trans_status_code
      t.float :n14th_trans_amount
      t.string :n14th_trans_type
      t.float :n14th_paid_amount
      t.date :n15th_trans_date
      t.string :n15th_invoice_number
      t.string :n15th_billing_trans_status_code
      t.float :n15th_trans_amount
      t.string :n15th_trans_type
      t.float :n15th_paid_amount


      t.timestamps null: false
    end
  end
end
