class CreateSc220Rec1EmployerDemographics < ActiveRecord::Migration
  def change
    create_table :sc220_rec1_employer_demographics do |t|
        t.integer :representative_number
        t.integer :representative_type
        t.string :description_ar
        t.integer :record_type
        t.integer :request_type
        t.integer :policy_type
        t.integer :policy_number
        t.integer :business_sequence_number
        t.string :federal_identification_number
        t.string :business_name
        t.string :trading_as_name
        t.string :in_care_name_contact_name
        t.string :address_1
        t.string :address_2
        t.string :city
        t.string :state
        t.string :zip_code
        t.string :zip_code_plus_4
        t.string :country_code
        t.string :county
        t.integer :currently_assigned_representative_number
        t.string :currently_assigned_representative_type
        t.integer :successor_policy_number
        t.integer :successor_business_sequence_number
        t.float :merit_rate
        t.string :group_code
        t.string :minimum_premium_percentage
        t.string :rate_adjust_factor
        t.date :em_effective_date
        t.float :n2nd_merit_rate
        t.string :n2nd_group_code
        t.string :n2nd_minimum_premium_percentage
        t.string :n2nd_rate_adjust_factor
        t.date :n2nd_em_effective_date
        t.float :n3rd_merit_rate
        t.string :n3rd_group_code
        t.string :n3rd_minimum_premium_percentage
        t.string :n3rd_rate_adjust_factor
        t.date :n3rd_em_effective_date
        t.float :n4th_merit_rate
        t.string :n4th_group_code
        t.string :n4th_minimum_premium_percentage
        t.string :n4th_rate_adjust_factor
        t.date :n4th_em_effective_date
        t.float :n5th_merit_rate
        t.string :n5th_group_code
        t.string :n5th_minimum_premium_percentage
        t.string :n5th_rate_adjust_factor
        t.date :n5th_em_effective_date
        t.float :n6th_merit_rate
        t.string :n6th_group_code
        t.string :n6th_minimum_premium_percentage
        t.string :n6th_rate_adjust_factor
        t.date :n6th_em_effective_date
        t.float :n7th_merit_rate
        t.string :n7th_group_code
        t.string :n7th_minimum_premium_percentage
        t.string :n7th_rate_adjust_factor
        t.date :n7th_em_effective_date
        t.float :n8th_merit_rate
        t.string :n8th_group_code
        t.string :n8th_minimum_premium_percentage
        t.string :n8th_rate_adjust_factor
        t.date :n8th_em_effective_date
        t.float :n9th_merit_rate
        t.string :n9th_group_code
        t.string :n9th_minimum_premium_percentage
        t.string :n9th_rate_adjust_factor
        t.date :n9th_em_effective_date
        t.float :n10th_merit_rate
        t.string :n10th_group_code
        t.string :n10th_minimum_premium_percentage
        t.string :n10th_rate_adjust_factor
        t.date :n10th_em_effective_date
        t.float :n11th_merit_rate
        t.string :n11th_group_code
        t.string :n11th_minimum_premium_percentage
        t.string :n11th_rate_adjust_factor
        t.date :n11th_em_effective_date
        t.float :n12th_merit_rate
        t.string :n12th_group_code
        t.string :n12th_minimum_premium_percentage
        t.string :n12th_rate_adjust_factor
        t.date :n12th_em_effective_date
        t.string :coverage_status
        t.date :coverage_effective_date
        t.date :coverage_end_date
        t.string :n2nd_coverage_status
        t.date :n2nd_coverage_effective_date
        t.date :n2nd_coverage_end_date
        t.string :n3rd_coverage_status
        t.date :n3rd_coverage_effective_date
        t.date :n3rd_coverage_end_date
        t.string :n4th_coverage_status
        t.date :n4th_coverage_effective_date
        t.date :n4th_coverage_end_date
        t.string :n5th_coverage_status
        t.date :n5th_coverage_effective_date
        t.date :n5th_coverage_end_date
        t.string :n6th_coverage_status
        t.date :n6th_coverage_effective_date
        t.date :n6th_coverage_end_date
        t.float :regular_balance_amount
        t.float :attorney_general_balance_amount
        t.float :appealed_balance_amount
        t.float :pending_balance_amount
        t.float :advance_deposit_amount

      t.timestamps null: false
    end
  end
end
