class AddRemainingFieldsToWeeklyMiras < ActiveRecord::Migration
  def change
    add_column :weekly_mira_detail_records, :claim_indicator, :string
    add_column :weekly_mira_detail_records, :claim_number, :string
    add_column :weekly_mira_detail_records, :claim_injury_date, :date
    add_column :weekly_mira_detail_records, :claim_filing_date, :date
    add_column :weekly_mira_detail_records, :claim_hire_date, :date
    add_column :weekly_mira_detail_records, :gender, :string
    add_column :weekly_mira_detail_records, :marital_status, :string
    add_column :weekly_mira_detail_records, :injured_worked_represented, :string
    add_column :weekly_mira_detail_records, :claim_status, :string
    add_column :weekly_mira_detail_records, :claim_status_effective_date, :date
    add_column :weekly_mira_detail_records, :claimant_name, :string
    add_column :weekly_mira_detail_records, :claim_manual_number, :integer
    add_column :weekly_mira_detail_records, :claim_sub_manual_number, :integer
    add_column :weekly_mira_detail_records, :industry_code, :integer
    add_column :weekly_mira_detail_records, :claim_type, :integer
    add_column :weekly_mira_detail_records, :claimant_date_of_birth, :date
    add_column :weekly_mira_detail_records, :claimant_age_at_injury, :string
    add_column :weekly_mira_detail_records, :claimant_date_of_death, :date
    add_column :weekly_mira_detail_records, :claim_activity_status, :string
    add_column :weekly_mira_detail_records, :claim_activity_status_effective_date, :date
    add_column :weekly_mira_detail_records, :prediction_status, :string
    add_column :weekly_mira_detail_records, :prediction_close_status_effective_date, :date
    add_column :weekly_mira_detail_records, :claimant_zip_code, :string
    add_column :weekly_mira_detail_records, :catastrophic_claim, :string
    add_column :weekly_mira_detail_records, :icd1_code, :float
    add_column :weekly_mira_detail_records, :icd1_code_type, :string, default: 'P'
    add_column :weekly_mira_detail_records, :icd2_code, :float
    add_column :weekly_mira_detail_records, :icd2_code_type, :string, default: 'S'
    add_column :weekly_mira_detail_records, :icd3_code, :float
    add_column :weekly_mira_detail_records, :icd3_code_type, :string, default: 'T'
    add_column :weekly_mira_detail_records, :average_weekly_wage, :float
    add_column :weekly_mira_detail_records, :claim_handicap_percent, :float
    add_column :weekly_mira_detail_records, :claim_handicap_percent_effective_date, :date
    add_column :weekly_mira_detail_records, :chiropractor, :string
    add_column :weekly_mira_detail_records, :physical_therapy, :string
    add_column :weekly_mira_detail_records, :salary_continuation, :string
    add_column :weekly_mira_detail_records, :last_date_worked, :date
    add_column :weekly_mira_detail_records, :estimated_return_to_work_date, :date
    add_column :weekly_mira_detail_records, :return_to_work_date, :date
    add_column :weekly_mira_detail_records, :mmi_date, :date
    add_column :weekly_mira_detail_records, :last_medical_date_of_service, :date
    add_column :weekly_mira_detail_records, :last_indemnity_period_end_date, :date
    add_column :weekly_mira_detail_records, :injury_or_litigation_type, :string
    add_column :weekly_mira_detail_records, :medical_ambulance_payments, :float
    add_column :weekly_mira_detail_records, :medical_clinic_or_nursing_home_payments, :float
    add_column :weekly_mira_detail_records, :medical_court_cost_payments, :float
    add_column :weekly_mira_detail_records, :medical_doctors_payments, :float
    add_column :weekly_mira_detail_records, :medical_drug_and_pharmacy_payments, :float
    add_column :weekly_mira_detail_records, :medical_emergency_room_payments, :float
    add_column :weekly_mira_detail_records, :medical_funeral_payments, :float
    add_column :weekly_mira_detail_records, :medical_hospital_payments, :float
    add_column :weekly_mira_detail_records, :medical_medical_device_payments, :float
    add_column :weekly_mira_detail_records, :medical_misc_payments, :float
    add_column :weekly_mira_detail_records, :medical_nursing_services_payments, :float
    add_column :weekly_mira_detail_records, :medical_prostheses_device_payments, :float
    add_column :weekly_mira_detail_records, :medical_prostheses_exam_payments, :float
    add_column :weekly_mira_detail_records, :medical_travel_payments, :float
    add_column :weekly_mira_detail_records, :medical_x_rays_and_radiology_payments, :float
    add_column :weekly_mira_detail_records, :total_medical_paid, :float
    add_column :weekly_mira_detail_records, :medical_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :total_medical_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_change_of_occupation_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_change_of_occupation_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_change_of_occupation_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_death_benefit_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_death_benefit_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_death_benefit_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_facial_disfigurement_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_facial_disfigurement_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_facial_disfigurement_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_living_maintenance_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_living_maintenance_wage_loss_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_living_maintenance_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_living_maintenance_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_permanent_partial_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_percent_permanent_partial_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_percent_permanent_partial_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_percent_permanent_partial_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_ptd_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_ptd_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_ptd_reserve_amount, :float
    add_column :weekly_mira_detail_records, :temporary_total_payments, :float
    add_column :weekly_mira_detail_records, :temporary_partial_payments, :float
    add_column :weekly_mira_detail_records, :wage_loss_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_temporary_total_reserve_prediction, :string
    add_column :weekly_mira_detail_records, :indemnity_temporary_total_reserve_amount, :float
    add_column :weekly_mira_detail_records, :indemnity_lump_sum_settlement_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_attorney_fee_payments, :float
    add_column :weekly_mira_detail_records, :indemnity_other_benefit_payments, :float
    add_column :weekly_mira_detail_records, :total_indemnity_paid_amount, :float
    add_column :weekly_mira_detail_records, :total_original_reserve_amount, :float
    add_column :weekly_mira_detail_records, :reduction_amount, :float
    add_column :weekly_mira_detail_records, :total_reserve_amount_for_rates, :float
    add_column :weekly_mira_detail_records, :reduction_reason, :string
    add_column :weekly_mira_detail_records, :total_indemnity_reserve_amount, :float
  end
end
